### ISSUE TITLE
my_user_config.h  ==vs== user_config_override.h

### ISSUE THREAD

**Issue by ozett** [phpcoder/tasmota-custom-integration#1]
[found your repo by chance](https://github.com/arendst/Tasmota/discussions/13673), it is great!

as i follow your instructions i was wondering
 if your deskription for `user_config_override.h` should better go to `my_user_config.h` ?

or does this break your setup?

as the copy from sample to `user_config_override.h` is nearly empty,
i have to transfer or change the existing `my_user_config.h`.
so that this file is not coming into play.

or some suggestions to make a clean start?

**Comment by ozett** [comment]
the readme.md is not fully clear for me [on this](https://github.com/phpcoder/tasmota-custom-integration#add-your-code-to-tasmota): 
How to #define the custom driver in `user_config_override.h` or `my_user_config.h`

The question seems: How to reference the driver for custom project in the `*.h`


<kbd>![image](https://user-images.githubusercontent.com/5937811/215854631-4609c97d-bd04-425c-ac6d-20d6c60a41b5.png)

**Comment by ozett** [comment]
is your `user_config_override.h` a working example?
what reference to use to include the xdrv_100_my_project_minimal.ino
a `#define, or the name ?`... 

edit: this does not explain how to use `custom`-driver..
https://tasmota.github.io/docs/Compile-your-build/#enabling-a-feature-in-tasmota


![image](https://user-images.githubusercontent.com/5937811/215857262-2c005339-5170-4bcd-bf6c-17a1828c6dda.png)

**Comment by ozett** [comment]
ok, this one is clear:
 
![image](https://user-images.githubusercontent.com/5937811/215864766-50003723-d210-4b55-b7df-b141e8bdfd5d.png)

https://tasmota.github.io/docs/Compile-your-build/#general-customization-principle

**Comment by ozett** [comment]
after some fiddling, two questions left:

do i need the `Project`-section in `user_config_override.h`
can i rename the driver? is there a convention to consider?

![image](https://user-images.githubusercontent.com/5937811/215870369-c11d8d65-bcb8-4cc5-9d8e-398e1017dc7b.png)

**Comment by phpcoder** [comment]
`#ifdef PROJECT` can be safely omitted. However, `#ifdef USE_MY_PROJECT` is the way to include your custom driver in the build.
Driver can be renamed, for custom integrations the numbers over xdrv_100 have been reserved if i remember correctly, but things may change as project evolves. When you use another number, some constants and function names should be renamed too.
Note, that this repository is made based on tasmota v10.0.0 and all driver examples follow conventions from that version.  Current version 12 requres some changes.

**Comment by ozett** [comment]
thanks for reply.
will try to use your framework with actual tasmota (v12.x).
looks like its working. 

thanks for providing this. its a great help.

**Comment by ozett** [comment]
after some digging, not all is clear.
but it seems, that the general approach should start with a custom environment in platform.io.
=> [platformio_tasmota_cenv.ini ](https://tasmota.github.io/docs/Compile-your-build/#sample-platformio_tasmota_cenvini)
that should than include the new-/custom driver.

(i have to spend some more time for going this way, but that seems better than your suggestion to change directly platform_override.ini)

IMPORTNAT HINT:
https://tasmota.github.io/docs/Compile-your-build/#defining-multiple-custom-firmwares

**Comment by ozett** [comment]
some settings still missing...  
hhmmmm , who ist an expert in custom-builds ?

![image](https://user-images.githubusercontent.com/5937811/216281491-46111e43-cdbb-4f59-9020-4bee5c91349a.png)

**Comment by ozett** [comment]
maybe it does not work to extend tasmota-lite
https://github.com/arendst/Tasmota/issues/17540#issuecomment-1367619684

edit: but maybe a workaround to copy some defaults from here:
https://github.com/arendst/Tasmota/blob/813233906b490742e925a448a0304eaac6179346/tasmota/include/tasmota_configurations.h#L661

**Comment by ozett** [comment]
looks better
<kbd> ![image](https://user-images.githubusercontent.com/5937811/216295270-6aba882e-299b-4444-bc09-93dfc2672309.png)

**Comment by ozett** [comment]
🟢  Firmware-Flag for `lite` seems to help using the lite-configurations form [tasmota_configurations.h](https://github.com/arendst/Tasmota/blob/813233906b490742e925a448a0304eaac6179346/tasmota/include/tasmota_configurations.h#L661)

<kbd>![image](https://user-images.githubusercontent.com/5937811/216297522-ec20fbf4-9c46-4f6e-b205-95a2bd264127.png)
