### ISSUE TITLE
How to make Driver appear in dropdown choice?

### ISSUE THREAD

**Issue by ozett** [phpcoder/tasmota-custom-integration#3]
your sample driver compiles and is active per default.
how can i make it a drop-down choice for the GPIO in the config section?

appreciate any hints..

<kbd>![image](https://user-images.githubusercontent.com/5937811/216252566-07aa6c0e-1d90-4ba8-a3a9-98992ecc4698.png)

**Comment by ozett** [comment]
sadly i dont know where to start? 
<kbd>![image](https://user-images.githubusercontent.com/5937811/216253005-b51b148c-14f7-4499-bc1a-c970a3ea2f61.png)

**Comment by phpcoder** [comment]
The best way to it is using [templates](https://tasmota.github.io/docs/Templates/).

**Comment by ozett** [comment]
> The best way to it is using templates

but so you can not control which driver is build into the firmware (?),
only predfine assignments of drivers to gpios ...
if i am correct, configureing `templates` will not change the choice of drivers in the dropdown, 
they still must be custom-build into the firmware beforehand..

**Comment by ozett** [comment]
the problem with the dropdown must have a connection to [UserSelectablePins](https://github.com/arendst/Tasmota/blob/c08561f67c722556655da7b8cbe1482d98aecd90/tasmota/include/tasmota_template.h#L26) 

same problem https://github.com/arendst/Tasmota/issues/5608

**Comment by ozett** [comment]
seems multiple steps to get the dropdown
https://github.com/arendst/Tasmota/issues/3315#issue-343935442
https://github.com/arendst/Tasmota/issues/5608#issuecomment-481313240

<kbd>![image](https://user-images.githubusercontent.com/5937811/216366622-ad5b6ef9-81f0-434b-962d-099a62026ff8.png)
